// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtj-VOqdnRE2Cxx7aDEUkpsIgxeb5sTvs',
    appId: '1:372278886039:web:3ae36daa354fd9965ab3d2',
    messagingSenderId: '372278886039',
    projectId: 'mini-social-app-def30',
    authDomain: 'mini-social-app-def30.firebaseapp.com',
    storageBucket: 'mini-social-app-def30.firebasestorage.app',
    measurementId: 'G-XXF7CZ2JNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuNzmEyDYRbSxhA80rKARVY6DJhSXM5gI',
    appId: '1:372278886039:android:aa37ac84537008ec5ab3d2',
    messagingSenderId: '372278886039',
    projectId: 'mini-social-app-def30',
    storageBucket: 'mini-social-app-def30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByIp_VsnfNHlIo-WV6pV6c8r_3lbl6nNM',
    appId: '1:372278886039:ios:3a15ca20dbff534b5ab3d2',
    messagingSenderId: '372278886039',
    projectId: 'mini-social-app-def30',
    storageBucket: 'mini-social-app-def30.firebasestorage.app',
    iosBundleId: 'com.example.miniSocialApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtj-VOqdnRE2Cxx7aDEUkpsIgxeb5sTvs',
    appId: '1:372278886039:web:aa5ccdc50b47fd1c5ab3d2',
    messagingSenderId: '372278886039',
    projectId: 'mini-social-app-def30',
    authDomain: 'mini-social-app-def30.firebaseapp.com',
    storageBucket: 'mini-social-app-def30.firebasestorage.app',
    measurementId: 'G-DJVFL0C3DW',
  );
}
